name: 'build and deploy react app'

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/pimpakarn26/my-bmi-project:latest .  # เปลี่ยนเป็น GitHub username และชื่อ repository ของคุณ

      - name: Verify React Build Output
        run: |
          CONTAINER_ID=$(docker create ghcr.io/pimpakarn26/my-bmi-project:latest)  # ใช้ชื่อ image ให้ถูกต้อง
          docker cp $CONTAINER_ID:/usr/share/nginx/html ./build  # React ใช้โฟลเดอร์ `build` ไม่ใช่ `dist`
          docker rm -v $CONTAINER_ID
          ls -la ./build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build  # Deploy จากโฟลเดอร์ build ที่ React สร้างขึ้น
